import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingBottom: 20,
    backgroundColor: "#0f1419",
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#1e293b",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerIcon: {
    width: 20,
    height: 20,
    borderRadius: 20,
    overflow: "hidden",
  },
  headerIconGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#fff",
    marginLeft: 12,
  },
  statusIndicator: {
    flexDirection: "row",
    alignItems: "center",
  },
  onlineIndicator: {
    width: 6,
    height: 6,
    borderRadius: 4,
    backgroundColor: "#10b981",
    marginRight: 6,
  },
  statusText: {
    fontSize: 10,
    color: "#10b981",
    fontWeight: "500",
  },
  chatContainer: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    paddingBottom: 120,
    flexGrow: 1,
  },
  chatBubbleContainer: {
    marginBottom: 24,
    bottom: 5,
  },
  userBubbleWrapper: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    marginBottom: 12,
  },
  userAvatar: {
    width: 25,
    height: 25,
    marginRight: 3,
    borderRadius: 16,
    backgroundColor: "#3b82f6",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  userText: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 22,
  },
  aiBubbleWrapper: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-end",
  },
  aiAvatar: {
    width: 25,
    height: 25,
    borderRadius: 16,
    marginRight: 5,
    overflow: "hidden",
  },
  aiAvatarGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  aiBubble: {
    maxWidth: "80%",
    backgroundColor: "#1e293b",
    borderRadius: 18,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#334155",
  },
  aiText: {
    color: "#e2e8f0",
    fontSize: 12,
    lineHeight: 22,
  },
  typingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#667eea",
    marginRight: 4,
  },
  typingText: {
    color: "#94a3b8",
    fontSize: 14,
    fontStyle: "italic",
    marginLeft: 8,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyIcon: {
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 16,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 24,
  },
  inputContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    paddingTop: 12,
    backgroundColor: "rgba(15, 20, 25, 0.95)",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    borderRadius: 24,
    bottom: 95,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#334155",
  },
  textInput: {
    flex: 1,
    color: "#fff",
    fontSize: 12,
    lineHeight: 22,
    maxHeight: 100,
    paddingVertical: 8,
  },
  sendButton: {
    alignSelf: "center",
    width: 28,
    height: 28,
    left: 10,
    borderRadius: 20,
    overflow: "hidden",
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
  sendButtonGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  editInput: {
    color: "#fff",
    fontSize: 14,
    backgroundColor: "#1e293b",
    borderRadius: 8,
    padding: 8,
    marginTop: 4,
  },

  editActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 4,
  },
  bubbleActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 8,
    gap: 12,
    opacity: 0.6, // Làm mờ để không nổi bật
  },

  actionButton: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.08)", // Background nhẹ
  },
  editActionButton: {
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  userBubble: {
    maxWidth: "80%",
    backgroundColor: "#3b82f6",
    borderRadius: 18,
    borderBottomRightRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  generatedImage: {
    width: 250,
    height: 250,
    borderRadius: 10,
    marginTop: 4,
    backgroundColor: "#e2e8f0",
  },
  imageContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  imageCaption: {
    fontSize: 12,
    color: "#94a3b8",
    fontStyle: "italic",
    textAlign: "center",
  },
  uploadButton: {
    alignSelf: "center"
},
});

export default styles;
